'''
Abstraction Constants
'''

ABSTRACTIONS = {
    'FIRST_NAME': 'VALID_FIRST_NAME',
    'LAST_NAME': 'VALID_LAST_NAME',
    'ORG': 'VALID_COMPANY_NAME',
    'EMAIL': 'VALID_EMAIL',
    'MONEY': 'MONEY',
    'BIRTHDAY': 'VALID_DATE',
    'USERNAME': 'VALID_USERNAME'
}
