language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install spacy
  - python -m spacy download en
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
