version: '3'

services:
  abstractor:
    build: ./
    ports:
      - "5000"
    restart: always
    depends_on:
      - "discoveryservice"
  discoveryservice:
    image: springcloud/eureka
    ports:
        - "8761:8761"